name: Build and Deploy

on:
  push:
    branches: [ "feature-cicd" ]
jobs:
  standup:
    uses: ./.github/workflows/terraform.yml
    secrets: inherit
  # deploy:
  #   needs: [ standup ]
  #   uses: ./.github/workflows/gke-deploy.yml