name: Build and Deploy Workflow

on:
  push:
    branches: [ "feature-cicd" ]
  
jobs: 
  terraform:
    name: Call Terraform Workflow
    uses: ./.github/workflows/terraform.yml
    with:
      region: "us-central1"
      network: "liatrio-vpc-01"
      subnetwork: "liatrio-vpc-01-subnet-01"
      ip_range_pods: "liatrio-vpc-01-subnet-01-pods"
      ip_range_services: "liatrio-vpc-01-subnet-01-services"
    secrets: inherit
   
  docker-build-publish: 
    name: Call Image Workflow
    uses: ./.github/workflows/docker-publish.yml
    with:
      dockerfile_path: "./deployment/docker/Dockerfile"
      image_tag: "berryfd/liatrio-webservice:latest"
    secrets: inherit

  deploy:
    needs: [ terraform, docker-build-publish ] 
    name: Call GKE Deployment Workflow
    uses: ./.github/workflows/gke-deploy.yml
    secrets: inherit
    with:
      kube_context: "./deployment/kube/"
      gke_cluster: "liatrio-gke-cluster"
      gke_region: "us-central1"
    