name: Build and Publish to Docker Hub

on:
    workflow_call:
        inputs:
            dockerfile_path:
                required: true
                type: string
            image_tag:
                required: true
                type: string
        secrets:
            DOCKER_USERNAME:
                required: false
            DOCKER_AUTH_TOKEN:
                required: false

env:
    DOCKERFILE_PATH: ${{ inputs.dockerfile_path }}
    IMAGE_TAG: ${{ inputs.image_tag }}

jobs:
    build-publish:
        name: Build and Publish Docker Image
        runs-on: ubuntu-latest
        environment: production

        permissions:
            contents: 'read'
        steps:
            # Checkout the repository to the GitHub Actions runner
            - name: Checkout
              uses: actions/checkout@v4
              with:
                    ref: ${{ github.ref }}
            
            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3
              with:
                buildkitd-flags: --debug

            - name: Login to Docker
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_AUTH_TOKEN }}
        
            # Build the Docker image
            - name: Build and Publish
              uses: docker/build-push-action@v5
              with:
                context: .
                file: ${{ env.DOCKERFILE_PATH }}
                tags: ${{ env.IMAGE_TAG }}
      