# This reusable workflow is designed to build docker image, and push it to docker-hub
name: Build and Publish to Docker Hub

on:
    # This workflow can only be called by another workflow 
    workflow_call:
        inputs:
            dockerfile_path:
                required: true
                type: string
            image_tag:
                required: true
                type: string
        secrets: 
            DOCKER_USERNAME:
                required: false # Even though they actually are required, inheriting the secret doesn't satisfy the 'required: true' and will fail.
            DOCKER_AUTH_TOKEN:
                required: false
# Passing inputs as ENV's for actions.
env:
    DOCKERFILE_PATH: ${{ inputs.dockerfile_path }}
    IMAGE_TAG: ${{ inputs.image_tag }}

jobs:
    build-publish:
        name: Build and Publish Docker Image
        runs-on: ubuntu-latest
        environment: production

        permissions:
            contents: 'read'
        steps:
            # Checkout the repository to the GitHub Actions runner
            - name: Checkout
              uses: actions/checkout@v4
              with:
                    ref: ${{ github.ref }}
            # Setup Go on machine
            - name: Setup Go
              uses: actions/setup-go@v4
              with:
                go-version: '^1.21.4'
            
            # Run unit tests
            - name: Run Tests
              run: go test -cover -v ./...

            # Setup Docker 
            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3
              with:
                buildkitd-flags: --debug

            # Authenticate with Docker Hub
            - name: Login to Docker
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_AUTH_TOKEN }}
        
            # Build and Push the Docker image
            - name: Build and Publish
              uses: docker/build-push-action@v5
              with:
                push: true
                context: .
                file: ${{ env.DOCKERFILE_PATH }}
                tags: ${{ env.IMAGE_TAG }}
      